# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Button(QtWidgets.QPushButton):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setMinimumSize(60, 60)

        self.color1 = QtGui.QColor(240, 53, 218)
        self.color2 = QtGui.QColor(61, 217, 245)

        self._animation = QtCore.QVariantAnimation(
            self,
            valueChanged=self._animate,
            startValue=0,
            endValue=120,
            duration=500
        )

        self._animation.setDirection(QtCore.QAbstractAnimation.Backward)
        self._animation.start()

    def _animate(self, value):
        qss = """
            font: 75 10pt "Microsoft YaHei UI";
            font-weight: bold;
            color: rgb(255, 255, 255);
        """
        grad = f"background-color: rgb({61 + value}, 215, 245)"
        qss += grad
        self.setStyleSheet(qss)

    def enterEvent(self, event):
        self._animation.setDirection(QtCore.QAbstractAnimation.Forward)
        self._animation.start()
        super().enterEvent(event)

    def leaveEvent(self, event):
        self._animation.setDirection(QtCore.QAbstractAnimation.Backward)
        self._animation.start()
        super().enterEvent(event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 191, 1000))
        self.widget.setStyleSheet("background: #a5a5a5;\n"
                                  "border-radius: 10px;\n"
                                  "border: 3px solid #757575;")
        self.widget.setObjectName("widget")
        self.main = Button(self.widget)
        self.main.setGeometry(QtCore.QRect(14, 12, 161, 41))
        self.main.setStyleSheet("font: 75 16pt \"Arial\";\n"
                                "background: #c5c5c5")
        self.main.setObjectName("main")
        self.main.setEnabled(False)
        self.main.setCheckable(True)
        self.main.setChecked(True)
        self.serversettings = Button(self.widget)
        self.serversettings.setGeometry(QtCore.QRect(14, 80, 161, 41))
        self.serversettings.setStyleSheet("font: 75 10pt \"Arial\";")
        self.serversettings.setObjectName("serversettings")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(220, 30, 1031, 961))
        self.scrollArea.setStyleSheet("background: #d5d5d5;\n"
                                      "border-radius: 30px;\n"
                                      "border: 3px solid #757575")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(
            QtCore.QRect(0, 0, 1025, 955))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.buttons = []
        for i in range(3):
            pushButton_3 = Button(self.scrollAreaWidgetContents)
            pushButton_3.setGeometry(QtCore.QRect(70 + 231 * i, 30, 201, 71))
            pushButton_3.setStyleSheet("font: 75 16pt \"Arial\";\n"
                                       "background: #a5a5a5")
            pushButton_3.setObjectName("pushButton_3")
            self.buttons.append(pushButton_3)
        i += 1
        self.pushButton_4 = Button(
            self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(70 + 231 * i, 30, 181, 71))
        self.pushButton_4.setStyleSheet("font: 75 16pt \"Arial\";\n"
                                        "background: #a5a5a5")
        self.pushButton_4.setObjectName("pushButton_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main.setText(_translate("MainWindow", "Главная"))
        self.serversettings.setText(_translate(
            "MainWindow", "Настройки сервера"))
        for i in self.buttons:
            i.setText(_translate("MainWindow", "Тест1"))
        self.pushButton_4.setText(_translate("MainWindow", "+"))
